alias nr='npm run'
alias nrb='npm run build'
alias nrt='npm run test'
alias jw='jest --watch'
alias jwb='jest --watch --bail'
alias jwbn='jest --watch --bail --no-coverage'
alias fuckwebpack='pkill -f "webpack" -9'
