#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname "$0")"/..

echo 'Installing various install.sh and install.bash files'

# find the installers and run them iteratively
find . -name install.sh | while read -r installer ; do sh -c "${installer}" ; done
find . -name install.bash | while read -r installer ; do sh -c "${installer}" ; done

echo
echo 'Done.'
