alias use-purs-0.11.7='ln -sf $INSTALLED/purescript-0.11.7/purescript/purs ~/.bin/purs'
alias use-purs-0.12='ln -sf $INSTALLED/purescript-0.12.0/purescript/purs ~/.bin/purs'

alias bi='bower install'
alias pp='psc-package'
alias ppb='psc-package build'
alias p='pulp --psc-package'
alias pu='pulp'
alias pub='pulp build'
alias puspe='pulp build --src-path ~/empty'
alias puit='pulp build --include test'
