alias reload!='. ~/.zshrc'
alias gemacs='open -a Emacs'
alias em='emacs'
alias ge='gemacs $1'
alias pb='pbcopy'
alias chrome-remote-debug='/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --remote-debugging-port=9222'
