alias reload!='. ~/.zshrc'
alias vi='vim'
alias nv="mvim"
alias emd='emacs --daemon'
alias emk='killall QUIT Emacs'
alias em='emacsclient -t'
alias ge='emacsclient -c'
alias pb='pbcopy'
alias chrome-remote-debug='/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --remote-debugging-port=9222'
alias recent='ls -lht | head -10'
alias ll='lstoless'
